# Copyright (c) 2015, Google Inc. Please see the AUTHORS file for details.
# All rights reserved. Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

install:
  - cinst -y dart-sdk
  - set PATH=%PATH%;C:\tools\dart-sdk\bin
  - set PATH=%PATH%;%APPDATA%\Pub\Cache\bin
  - pub get

clone_depth: 1

build: off

test_script:
  - dart tool\grind.dart buildbot
