name: grinder
# This version must be updated in tandem with the lib/src/cli.dart version.
version: 0.9.2
description: Grinder is a task runner for Dart, helping to define and automate common project workflows.

homepage: https://github.com/google/grinder.dart

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cli_util: ^0.3.0
  glob: ^2.0.0
  meta: ^1.4.0
  path: ^1.8.0
  collection: ^1.15.0

dev_dependencies:
  lints: '>=1.0.0 <3.0.0'
  test: ^1.17.0

executables:
  grind: grinder
