name: grinder
version: 0.6.0
author: Devon Carew <devoncarew@google.com>
description: Grinder - a task based, dependency aware build system.
homepage: https://github.com/google/grinder.dart
environment:
  sdk: ">=1.0.0 <2.0.0"
dependencies:
  args: any
  quiver: ">=0.18.0 <0.19.0"
dev_dependencies:
  unittest: any
