name: grinder
# This version must be updated in tandem with the lib/src/cli.dart version.
version: 0.8.3
description: Dart workflows, automated.

homepage: https://github.com/google/grinder.dart
authors:
- Devon Carew <devoncarew@google.com>
- Sean Eagan <seaneagan1@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  cli_util: ^0.1.2
  glob: ^1.0.0
  path: ^1.0.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.0.0

executables:
  grind: grinder
